### ISSUE TITLE
docs do not build on RTD

### ISSUE THREAD

**Issue by prjemian** [prjemian/assign_gup#11]
RTD: http://assign-gup.readthedocs.org

**Comment by prjemian** [comment]
actually, some of the module documentation is not building, such as about and general_mvc_model  (and others0

**Comment by prjemian** [comment]
lots of these errors:

/home/docs/checkouts/readthedocs.org/user_builds/assign-gup/checkouts/latest/docs/source/source_code/about.rst:4: WARNING: autodoc: failed to import module u'about'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/assign-gup/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    **import**(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/assign-gup/checkouts/latest/src/Assign_GUP/about.py", line 8, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

**Comment by prjemian** [comment]
https://duckduckgo.com/?q=read+the+docs+%3A+how+to+mock+PyQt4&t=ffsb

see these two articles:
- http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
- http://stackoverflow.com/questions/25960309/sphinx-doc-automodule-with-mock-imports

The second one shows how to Mock out PyQt4, class-by-class.  Ugly.  Must be a better way.

**Comment by prjemian** [comment]
So far, the ImportError is gone for about.py, plainTextEdit.py, and resources.py but still no links to marked up source code appear on RTD

**Comment by prjemian** [comment]
another read:
http://blog.rtwilson.com/how-to-make-your-sphinx-documentation-compile-with-readthedocs-when-youre-using-numpy-and-scipy/

**Comment by prjemian** [comment]
No.  That's a general motivation to use Mock
