### ISSUE TITLE
documentation has build errors

### ISSUE THREAD

**Issue by prjemian** [prjemian/assign_gup#26]
```
C:\Users\Pete\Documents\eclipse\assign_gup\docs>make html
make html
Running Sphinx v1.3.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 35 source files that are out of date
updating environment: [config changed] 35 added, 1 changed, 0 removed
reading sources... [100%] source_code/xml_utility                              
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\about.rst:4: WARNING: autodoc: failed to import module u'about'; the following exception was raised:
Traceback (most recent call last):
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.3.1-py2.7.egg\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\about.py", line 16, in <module>
    import __init__
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\__init__.py", line 54, in <module>
    from ._version import get_versions
ValueError: Attempted relative import in non-package
looking for now-outdated files... none found
pickling environment... C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\history.rst:2: SEVERE: Duplicate ID: "module-history".
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\main_window.rst:4: WARNING: autodoc: failed to import module u'main_window'; the following exception was raised:
Traceback (most recent call last):
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.3.1-py2.7.egg\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\main_window.py", line 18, in <module>
    import about
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\about.py", line 16, in <module>
    import __init__
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\__init__.py", line 54, in <module>
    from ._version import get_versions
ValueError: Attempted relative import in non-package
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\proposal.rst:2: SEVERE: Duplicate ID: "module-proposal".
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\resources.rst:2: SEVERE: Duplicate ID: "module-resources".
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\reviewer.rst:2: SEVERE: Duplicate ID: "module-reviewer".
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\settings.rst:4: WARNING: autodoc: failed to import module u'settings'; the following exception was raised:
Traceback (most recent call last):
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.3.1-py2.7.egg\sphinx\ext\autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\settings.py", line 40, in <module>
    import __init__
  File "C:\Users\Pete\Documents\eclipse\assign_gup\src\Assign_GUP\__init__.py", line 54, in <module>
    from ._version import get_versions
ValueError: Attempted relative import in non-package
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\signals.rst:2: SEVERE: Duplicate ID: "module-signals".
C:\Users\Pete\Documents\eclipse\assign_gup\docs\source\source_code\topics.rst:2: SEVERE: Duplicate ID: "module-topics".
done
checking consistency... done
preparing documents... done
writing output... [100%] source_code/xml_utility                               
generating indices... genindex py-modindex
highlighting module code... [100%] prop_mvc_view                               
writing additional pages... search
copying images... [100%] resources/topics_editor.jpg                           
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 9 warnings.

Build finished. The HTML pages are in build/html.

C:\Users\Pete\Documents\eclipse\assign_gup\docs>
```

**Comment by prjemian** [comment]
this article was not helpful:
http://stackoverflow.com/questions/16471032/how-do-i-avoid-severe-duplicate-id-warnings-for-my-autodocd-modules-in-sphin
