### ISSUE TITLE
div by zero error

### ISSUE THREAD

**Issue by prjemian** [prjemian/assign_gup#32]
with a new project (no proposals or reviewers or topics), this error:

```
pi@prjpi:~ $ Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Assign_GUP/main_window.py", line 598, in doSummaryReport
    self.summary_window = report_summary.Report(None, self.agup, self.settings)
  File "/usr/local/lib/python2.7/dist-packages/Assign_GUP/report_summary.py", line 49, in __init__
    text = self.makeText()
  File "/usr/local/lib/python2.7/dist-packages/Assign_GUP/report_summary.py", line 77, in makeText
    mean = float(len(self.agup.proposals)) / float(len(self.agup.reviewers))
ZeroDivisionError: float division by zero
```

**Comment by prjemian** [comment]
the error is from the summary report
