### ISSUE TITLE
problem entering new topics

### ISSUE THREAD

**Issue by prjemian** [prjemian/assign_gup#48]
2016-03-08 09:30:03.202 python[9327:306102] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2016-03-08 09:30:10.271 python[9327:306102] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2016-03-08 09:30:48.875 python[9327:306102] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2016-03-08 09:31:18.580 python[9327:306102] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 94, in on_item_clicked
    self.selectModelByIndex(index, self.prior_selection_index)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 177, in selectModelByIndex
    self.editReviewer(sort_name, prev)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 138, in editReviewer
    self.details_panel.setTopic(topic, value)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/reviewer_details.py", line 72, in setTopic
    raise KeyError, 'unknown Topic: ' + key
KeyError: 'unknown Topic: Batteries'
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 94, in on_item_clicked
    self.selectModelByIndex(index, self.prior_selection_index)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 177, in selectModelByIndex
    self.editReviewer(sort_name, prev)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 138, in editReviewer
    self.details_panel.setTopic(topic, value)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/reviewer_details.py", line 72, in setTopic
    raise KeyError, 'unknown Topic: ' + key
KeyError: 'unknown Topic: Batteries'
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 94, in on_item_clicked
    self.selectModelByIndex(index, self.prior_selection_index)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 177, in selectModelByIndex
    self.editReviewer(sort_name, prev)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 138, in editReviewer
    self.details_panel.setTopic(topic, value)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/reviewer_details.py", line 72, in setTopic
    raise KeyError, 'unknown Topic: ' + key
KeyError: 'unknown Topic: Batteries'
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 94, in on_item_clicked
    self.selectModelByIndex(index, self.prior_selection_index)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 177, in selectModelByIndex
    self.editReviewer(sort_name, prev)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/revu_mvc_view.py", line 138, in editReviewer
    self.details_panel.setTopic(topic, value)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/reviewer_details.py", line 72, in setTopic
    raise KeyError, 'unknown Topic: ' + key
KeyError: 'unknown Topic: Batteries'

**Comment by prjemian** [comment]
"The topics appear after a restart."

This is a bug, probably specific to MacOSX

**Comment by prjemian** [comment]
On Tue, Mar 8, 2016 at 10:11 AM, Pete Jemian jemian@anl.gov wrote:

```
I'll look into that one.  That's new.  Not sure which code generates the message "modalSession has been exited ...", certainly a library I'm calling.  The "KeyError" exceptions are a consequence.

How did you move from the "Edit Topics" window to the "Edit Reviewers window?  Perhaps this?  Close the "edit topics" window by clicking the close window icon in the window frame, then open the "edit reviewers" window from the menu?

This might be an issue specific to MacOSX.  When I do it on Windows (add the Batteries topic, then edit reviewers), no exceptions were recorded and the new topic is shown.  No problem on Linux, either.
```

**Comment by prjemian** [comment]
Another observation: it seems that the new topics do not show up in whatever editor is opened first. That is if I add the topics, and then open proposals editor, they are not in the list in that window. If I open the reviewers window after opening the proposals window, they are there in the reviewers window.

**Comment by prjemian** [comment]
Could not reproduce the initial errors:

```
2016-03-08 09:31:18.580 python[9327:306102] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```

probably, #50 has fixed the problem of the new topics not appearing in the topics editor properly
