### ISSUE TITLE
unhandled non-ASCII character

### ISSUE THREAD

**Issue by prjemian** [prjemian/assign_gup#55]
When I try to view the assignments report, the window does not open and I get the following error printed to the terminal:

```
localhost:~ username$ assign_gup
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/main_window.py", line 669, in doAssignmentsReport
    self.settings)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/report_assignments.py", line 34, in __init__
    text = self.makeText()
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/report_assignments.py", line 56, in makeText
    return tbl.reST()
  File "/Users/username/anaconda/lib/python2.7/site-packages/pyRestTable/rest_table.py", line 143, in reST
    }[fmt](indentation)
  File "/Users/username/anaconda/lib/python2.7/site-packages/pyRestTable/rest_table.py", line 148, in simple_table
    width = self.find_widths()
  File "/Users/username/anaconda/lib/python2.7/site-packages/pyRestTable/rest_table.py", line 283, in find_widths
    row_width = [max(map(len, str(_).split("\n"))) for _ in row]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 74: ordinal not in range(128)
```

**Comment by prjemian** [comment]
see:  http://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by prjemian** [comment]
still not fixed, posted interim work-around in 094cae6

**Comment by prjemian** [comment]
still not fixed, so re-open it

**Comment by prjemian** [comment]
still not done
