### ISSUE TITLE
Cannot write project file with current version!

### ISSUE THREAD

**Issue by prjemian** [prjemian/assign_gup#57]
Actually, it seems I am no longer able to save the project file since the update. I didn't realize this until I opened the file and found it had reverted to a previous version. Luckily I took a screen shot of the assignments, otherwise I would be really out of luck. The error that gets printed to the terminal is below.

```
localhost:~ username$ assign_gup
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/main_window.py", line 511, in doSave
    self.agup.write(filename)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/agup_data.py", line 92, in write
    self.proposals.writeXmlNode(root)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/prop_mvc_data.py", line 109, in writeXmlNode
    prop.writeXmlNode(etree.SubElement(node, 'Proposal'))
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/proposal.py", line 80, in writeXmlNode
    etree.SubElement(specified_node, tag).text = self.getKey(tag)
  File "lxml.etree.pyx", line 951, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:46353)
  File "apihelpers.pxi", line 695, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20953)
  File "apihelpers.pxi", line 683, in lxml.etree._createTextNode (src/lxml/lxml.etree.c:20829)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src/lxml/lxml.etree.c:27125)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/main_window.py", line 511, in doSave
    self.agup.write(filename)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/agup_data.py", line 92, in write
    self.proposals.writeXmlNode(root)
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/prop_mvc_data.py", line 109, in writeXmlNode
    prop.writeXmlNode(etree.SubElement(node, 'Proposal'))
  File "/Users/username/anaconda/lib/python2.7/site-packages/Assign_GUP/proposal.py", line 80, in writeXmlNode
    etree.SubElement(specified_node, tag).text = self.getKey(tag)
  File "lxml.etree.pyx", line 951, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:46353)
  File "apihelpers.pxi", line 695, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20953)
  File "apihelpers.pxi", line 683, in lxml.etree._createTextNode (src/lxml/lxml.etree.c:20829)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src/lxml/lxml.etree.c:27125)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by prjemian** [comment]
developed and tested OK on Windows
tested OK on linux

**Comment by prjemian** [comment]
tested OK on MacOSX
this is fixed
