### ISSUE TITLE
unexpected exception on new install

### ISSUE THREAD

**Issue by strzalka00** [prjemian/assign_gup#66]
```
(15064,Assign_GUP,2017-02-27 10:32:01.931000) startup
(15064,Assign_GUP,2017-02-27 10:32:02.078000) log_file         = None
(15064,Assign_GUP,2017-02-27 10:32:02.079000) interest level   = no logging
(15064,Assign_GUP,2017-02-27 10:32:02.080000) user             = strzalka
(15064,Assign_GUP,2017-02-27 10:32:02.091000) host             = sec8pc01
(15064,Assign_GUP,2017-02-27 10:32:02.091000) program          = C:\Users\strzalka\AppData\Local\Continuum\Anaconda\Scripts\Assign_GUP
(15064,Assign_GUP,2017-02-27 10:32:02.092000) program filename = Assign_GUP
(15064,Assign_GUP,2017-02-27 10:32:02.093000) PID              = 15064
(15064,Assign_GUP,2017-02-27 10:35:47.529000) Traceback (most recent call last):
(15064,Assign_GUP,2017-02-27 10:35:47.531000)   File "c:\users\strzalka\appdata\local\continuum\anaconda\lib\site-packages\Assign_GUP\main_window.py", line 420, in importProposals
(15064,Assign_GUP,2017-02-27 10:35:47.532000)     self.agup.importProposals(filename)
(15064,Assign_GUP,2017-02-27 10:35:47.533000)   File "c:\users\strzalka\appdata\local\continuum\anaconda\lib\site-packages\Assign_GUP\agup_data.py", line 103, in importProposals
(15064,Assign_GUP,2017-02-27 10:35:47.534000)     props.importXml(xmlFile)
(15064,Assign_GUP,2017-02-27 10:35:47.536000)   File "c:\users\strzalka\appdata\local\continuum\anaconda\lib\site-packages\Assign_GUP\prop_mvc_data.py", line 82, in importXml
(15064,Assign_GUP,2017-02-27 10:35:47.537000)     alt_schema=XML_SCHEMA_FILE,
(15064,Assign_GUP,2017-02-27 10:35:47.539000)   File "parser.pxi", line 18, in lxml.etree.ParseError.__init__ (src\lxml\lxml.etree.c:89005)
(15064,Assign_GUP,2017-02-27 10:35:47.540000) TypeError: __init__() takes exactly 5 positional arguments (2 given)
(15064,Assign_GUP,2017-02-27 10:35:55.151000) imported proposals file: C:/Users/strzalka/Documents/APS/PRP_SAXS/2017_2/2007-2-proposals.xml
(15064,Assign_GUP,2017-02-27 10:37:42.545000) opening issues URL in default browser
```

**Comment by prjemian** [comment]
Three problems here, actually.

* [x] XML file was improperly formatted.  First, it was HTML version of the XML, then it had a blank line at the start before the XML declaration.  Fixing both of those allowed the code to run.
* [x] actual exception raised in `xml_utility.readValidXmlDoc()`, line 56 was an XML syntax error and the correct message is not passed to the GUI -- the GUI summarizes, incorrectly, that the file is not a proposals file
* [x] the reported exception was raised during the handling of the original exception!

**Comment by prjemian** [comment]
The program *could* edit the XML internally but that changes the XML line number references.  If the XML file starts with a blank line, that **is** an XML syntax error.

So, read the XML file as given.

**Comment by prjemian** [comment]
removed the `try .. except` clause from `xml_utility.readValidXmlDoc` to expose the original exception
